[tools]
argocd = "latest"
azure = "latest"
azure-kubelogin = "latest"
claude = "latest"
devcontainer-cli = "latest"
docker-cli = "latest"
docker-compose = "latest"
docker-slim = "latest"
esc = "latest"
fzf = "latest"
github-cli = "latest"
go = "latest"
helm = "latest"
jq = "latest"
k9s = "latest"
krew = "latest"
kubectl = "latest"
kubelogin = "latest"
kustomize = "latest"
minikube = "latest"
neovim = "latest"
node = "latest"
pipx = "latest"
pnpm = "latest"
pre-commit = "latest"
prettier = "latest"
pulumi = "latest"
python = "latest"
shellcheck = "latest"
yq = "latest"